apiVersion: apps/v1
kind: Deployment
metadata:
  name: subject-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: subject-label
  template: 
    metadata:
      labels:
        app: subject-label
    spec: 
      containers:
      - name: subject
        image: subject-service:3.1 
        resources: 
          requests: 
            memory: "128Mi"
            cpu: "500m"
          limits: 
            memory: "256Mi"
            cpu: "1000m"
        ports:
        - containerPort: 8089
