apiVersion: v1
kind: Pod
metadata:
  name: emptydir-pod
  labels:
    name: emptydir-label
spec:
  containers:
  - name: ubuntu
    image: ubuntu:latest
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    command:
    - cat
    tty: true
    # 아래 선언한 볼륨을 컨테이너 설정에서 불러와서 사용한다.
    volumeMounts:
    - name: emptydir-volume
      mountPath: /root/tmp
  - name: alpine
    image: alpine:latest
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    command:
    - cat
    tty: true
    # 아래 선언한 볼륨을 컨테이너 설정에서 불러와서 사용한다.
    volumeMounts:
    - name: emptydir-volume
      mountPath: /root/tmp
    # 사용하려는 볼륨들을 먼저 선언(정의)한다
  volumes:
  - name: emptydir-volume
    emptyDir: {}