apiVersion: v1
kind: Pod
metadata:
  name: hostpath-pod
  labels:
    name: hostpath-label
spec:
  containers:
  - name: ubuntu
    image: ubuntu:latest
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    command:
    - cat
    tty: true
    volumeMounts:
    - name: hostpath-volume
      mountPath: /root/tmp
  volumes:
  - name: hostpath-volume
    hostPath: 
      path: /tmp/docker-desktop-root/run/desktop/mnt/host/c/Users/Playdata/volume-test
